name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # run manually

env:
  DOCKER_TAGNAME: bertsky/ocrd_detectron2

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - # Activate cache export feature to reduce build time of image
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: make docker DOCKER_TAG=${{ env.DOCKER_TAGNAME }}
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to Dockerhub
      run: docker push ${{ env.DOCKER_TAGNAME }}
    - name: Alias the Docker image for GHCR
      run: docker tag ${{ env.DOCKER_TAGNAME }} ghcr.io/${{ env.DOCKER_TAGNAME }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image to Github Container Registry
      run: docker push ghcr.io/${{ env.DOCKER_TAGNAME }}
